### ISSUE TITLE
Joomla 3.8: Update on Socialmeta 1.1 don't work

### ISSUE THREAD

**Issue by ghost** [vistamedia/socialmeta#11]
Since Update on Joomla 3.8 get Update Notification:
![bildschirmfoto 2017-09-20 um 08 55 51](https://user-images.githubusercontent.com/8235763/30630655-cef6f784-9de1-11e7-847f-bdee934893ac.jpg)
After Update the Notification display again.

**Comment by vistamedia** [comment]
Hi Franz and thanks for submitting the issue. It happens because I used the beta channel instead of the dev channel in the update manager.
It should be fixed now.

**Comment by ghost** [comment]
I update, cleared Browser-Cache, no CDN - get Update Notifcation.

**Comment by vistamedia** [comment]
What channel do you use in your update manager?

**Comment by ggppdk** [comment]
https://raw.githubusercontent.com/vistamedia/socialmeta/master/updates/plg_socialmeta_updates.xml

has 2 `<update>...</update>` 
1 with 'tags' 'stable' and version number 1.0
and
1 with 'tags' 'dev' with version number 1.1

but master branch XML file has version number 1.0 , so you are continuesly prompted to update to version 1.1 which does not exist

another question is why i am asked to update (for tags 'dev') since my minimum stability is "stable"

**Comment by vistamedia** [comment]
Hummm, it's probably a bug from J!3.8 (which doesn't seem to care about the channels), it does not happens with J!3.7.5
I completely removed the second <update> until the bug of the com_installer is fixed ;)

**Comment by ghost** [comment]
Thanks @vistamedia, Notification is gone.
